language: java
install: mvn install -DskipTests=true
script: mvn test DskipTests=true -DsuiteXmlFile=src/test/resources/travisTestNG.xml
jdk:
  - openjdk7
after_script:
  - cat target/surefire-reports/*.txt