language: java
install: mvn install -DskipTests=true
script: mvn test -DjenkinsOperatingSystem=linux -DjenkinsBrowser=html -DjenkinsRunLocation=local
jdk:
  - openjdk7
after_script:
  - cat target/surefire-reports/TestSuite.txt